apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.secretName }}
type: Opaque
stringData:
  DB_NAME: {{ .Values.postgres.database | quote }}
  DB_USER: {{ .Values.postgres.username | quote }}
  DB_PASSWORD: {{ .Values.postgres.password | quote }}
